export const AppIcons = {
  RELOAD: 'reload',
  SEARCH: 'magnify',
  DOTS_CIRCLE: 'dots-circle',
  TRANSLATE: 'translate',
  SETTINGS: 'cog',
  PLUS: 'plus',
  CLOSE: 'close-circle',
  EDIT: 'pencil',
  VIEW: 'eye',
  DELETE: 'delete',
  FILTER: 'filter',
  LOGOUT: 'logout',
  FILTER_OUTLINE: 'filter-outline',
  FILTER_REMOVE: 'filter-remove',
  VALID_FORM: 'check',
  INVALID_FORM: 'alert-circle-outline',
  MORE_DETAILS: 'information-outline',
  CANCEL: 'cancel',
  TABLE_CANCEL: 'table-cancel',
  BOOK_CANCEL: 'book-cancel',
  BOOK_CANCEL_OUTLINE: 'book-cancel-outline',
  SITE_MAP: 'sitemap',
  SITE_MAP_OUTLINE: 'sitemap-outline',
  SERVICES: 'face-agent',
  GLOBAL_SETTING: 'cogs',
  HISTORY: 'history',
  ARROW_LEFT: 'arrow-left-circle-outline',
  ARROW_RIGHT: 'arrow-right-circle-outline',
};

export type AppIconsType = typeof AppIcons;
