import {
  anyFieldsHasLength,
  compareFromTo,
  decimalValidator,
  maxValueValidator,
  maxLengthValidator,
  minLengthValidator,
  minvValueValidator,
  numberValidator,
  patternValidator,
  requiredArrayValidator,
  requiredValidator,
  uniqueValidator,
  validateFieldsStatus,
  validateSum,
  passwordEqualConfirm,
} from '@validators/validation-utils';

export const CustomValidators = {
  validateFieldsStatus: validateFieldsStatus,
  validateSum: validateSum,
  required: requiredValidator,
  requiredArray: requiredArrayValidator,
  pattern: patternValidator,
  number: numberValidator,
  decimal: decimalValidator,
  minLength: minLengthValidator,
  maxLength: maxLengthValidator,
  anyFieldsHasLength,
  unique: uniqueValidator,
  compareFromTo: compareFromTo,
  minValue: minvValueValidator,
  maxValue: maxValueValidator,
  passwordEqualConfirm: passwordEqualConfirm,
};
